# Generated by Django 2.2.23 on 2021-05-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210513_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='spells_bonus_lvl0',
            field=models.TextField(),
        ),
    ]
