# Generated by Django 2.2.9 on 2021-09-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210520_0750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='character',
            new_name='Сharacter',
        ),
    ]
